apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: osac-aap-base

resources:
  - aap.yaml
  - osac-sa.yaml
  - job.yaml
  - template-publisher.yaml

labels:
- pairs:
    osac.openshift.io/project: osac-aap
