---
- name: Teardown hostpool infrastructure from a HostPool
  hosts: localhost
  gather_facts: false

  vars:
    hostpool: "{{ ansible_eda.event.payload }}"
    osac_fulfillment_service_uri: "{{ lookup('env', 'OSAC_FULFILLMENT_SERVICE_URI', default='https://fulfillment-api:8000') }}"

  pre_tasks:
    - name: Show hostpool values
      ansible.builtin.debug:
        var: hostpool

    - name: Determine working namespace
      ansible.builtin.include_role:
        name: osac.service.hostpool_working_namespace
      vars:
        hostpool_working_namespace_hostpool_name: "{{ hostpool.metadata.name }}"

  tasks:
    - name: Delete hostpool infrastructure
      ansible.builtin.import_role:
        name: osac.service.hostpool_infra
      vars:
        hostpool_infra_state: absent
        hostpool_infra_name: "{{ hostpool.metadata.name }}"
        hostpool_infra_namespace: "{{ hostpool_working_namespace }}"

    - name: Remove infrastructure finalizer
      ansible.builtin.include_role:
        name: osac.service.finalizer
      vars:
        finalizer_state: absent
        finalizer_name: "{{ hostpool_infrastructure_finalizer }}"
        finalizer_target:
          api_version: "{{ item.api_version }}"
          kind: "{{ item.kind }}"
          namespace: "{{ item.namespace | default(omit) }}"
          name: "{{ item.name }}"
      loop:
        - api_version: osac.openshift.io/v1alpha1
          kind: HostPool
          namespace: "{{ lookup('env', 'POD_NAMESPACE') }}"
          name: "{{ hostpool.metadata.name }}"
        - api_version: v1
          kind: Namespace
          name: "{{ hostpool_working_namespace }}"
