cluster_order_label: "osac.openshift.io/clusterorder"
cluster_order_infrastructure_finalizer: "osac.openshift.io/infrastructure"

compute_instance_label: "osac.openshift.io/computeinstance"
compute_instance_osac_finalizer: "osac.openshift.io/computeinstance-aap"

hostpool_label: "osac.openshift.io/hostpool"
hostpool_infrastructure_finalizer: "osac.openshift.io/infrastructure"

host_uuid_label: "osac.openshift.io/host-uuid"
